import type { Cultivo } from '../dominio/tipos'

export const CULTIVOS: Cultivo[] = [
  {
    id: 'tomate', nombreComun: 'Tomate', nombreCientifico: 'Solanum lycopersicum',
    icono: '🍅', familia: 'solanáceas', tipo: 'fruto',
    tempMinGerminacion: 12, tempOptima: 22, toleranciaHelada: 'sensible',
    texturaPreferida: ['franco'], phMin: 6, phMax: 6.8, drenajeRequerido: 'bueno',
    metodo: 'semillero_trasplante', sol: 'pleno_sol',
    distanciaPlantaCm: 50, distanciaLineaCm: 60, alturaCm: 150,
    diasACosecha: 90, rendimientoPorPlanta: 2.5, unidad: 'kg', ventana: 'continua', ventanaDias: 60,
    companeras: ['albahaca', 'lechuga'], antagonistas: ['patata'],
    riego: 'Riego regular y constante; evitar mojar la hoja.', plagas: 'Mildiu y pulgón; airear y vigilar.',
    notas: 'Entutorar y podar brotes axilares.',
  },
  {
    id: 'lechuga', nombreComun: 'Lechuga', nombreCientifico: 'Lactuca sativa',
    icono: '🥬', familia: 'compuestas', tipo: 'hoja',
    tempMinGerminacion: 5, tempOptima: 16, toleranciaHelada: 'resistente',
    texturaPreferida: ['franco', 'arenoso'], phMin: 6, phMax: 7, drenajeRequerido: 'medio',
    metodo: 'siembra_directa', sol: 'semisombra',
    distanciaPlantaCm: 25, distanciaLineaCm: 30, alturaCm: 25,
    diasACosecha: 55, rendimientoPorPlanta: 1, unidad: 'unidades', ventana: 'puntual',
    companeras: ['zanahoria', 'tomate'], antagonistas: [],
    riego: 'Riego frecuente y ligero; no debe faltar humedad.', plagas: 'Babosas y pulgón.',
    notas: 'Cosechar antes de que suba a flor.',
  },
  {
    id: 'pimiento', nombreComun: 'Pimiento', nombreCientifico: 'Capsicum annuum',
    icono: '🫑', familia: 'solanáceas', tipo: 'fruto',
    tempMinGerminacion: 15, tempOptima: 24, toleranciaHelada: 'sensible',
    texturaPreferida: ['franco'], phMin: 6, phMax: 7, drenajeRequerido: 'bueno',
    metodo: 'semillero_trasplante', sol: 'pleno_sol',
    distanciaPlantaCm: 40, distanciaLineaCm: 50, alturaCm: 70,
    diasACosecha: 100, rendimientoPorPlanta: 1.5, unidad: 'kg', ventana: 'continua', ventanaDias: 50,
    companeras: ['albahaca'], antagonistas: [],
    riego: 'Riego regular; sensible a la falta de agua en fructificación.', plagas: 'Pulgón y araña roja.',
    notas: 'Necesita calor; proteger del viento fuerte.',
  },
  {
    id: 'calabacin', nombreComun: 'Calabacín', nombreCientifico: 'Cucurbita pepo',
    icono: '🥒', familia: 'cucurbitáceas', tipo: 'fruto',
    tempMinGerminacion: 13, tempOptima: 24, toleranciaHelada: 'sensible',
    texturaPreferida: ['franco'], phMin: 6, phMax: 7, drenajeRequerido: 'bueno',
    metodo: 'siembra_directa', sol: 'pleno_sol',
    distanciaPlantaCm: 80, distanciaLineaCm: 100, alturaCm: 60,
    diasACosecha: 50, rendimientoPorPlanta: 3, unidad: 'kg', ventana: 'continua', ventanaDias: 70,
    companeras: ['judia'], antagonistas: ['patata'],
    riego: 'Necesita bastante agua; riego abundante en verano.', plagas: 'Oídio; airear.',
    notas: 'Ocupa mucho espacio; cosechar tiernos y a menudo.',
  },
  {
    id: 'zanahoria', nombreComun: 'Zanahoria', nombreCientifico: 'Daucus carota',
    icono: '🥕', familia: 'umbelíferas', tipo: 'raiz',
    tempMinGerminacion: 7, tempOptima: 18, toleranciaHelada: 'resistente',
    texturaPreferida: ['arenoso', 'franco'], phMin: 6, phMax: 7, drenajeRequerido: 'bueno',
    metodo: 'siembra_directa', sol: 'pleno_sol',
    distanciaPlantaCm: 8, distanciaLineaCm: 25, alturaCm: 30,
    diasACosecha: 80, rendimientoPorPlanta: 0.12, unidad: 'kg', ventana: 'puntual',
    companeras: ['lechuga', 'cebolla'], antagonistas: [],
    riego: 'Humedad constante hasta germinar; luego moderado.', plagas: 'Mosca de la zanahoria.',
    notas: 'Suelo suelto y sin piedras para raíces rectas.',
  },
  {
    id: 'cebolla', nombreComun: 'Cebolla', nombreCientifico: 'Allium cepa',
    icono: '🧅', familia: 'liliáceas', tipo: 'bulbo',
    tempMinGerminacion: 8, tempOptima: 18, toleranciaHelada: 'resistente',
    texturaPreferida: ['franco'], phMin: 6, phMax: 7, drenajeRequerido: 'bueno',
    metodo: 'siembra_directa', sol: 'pleno_sol',
    distanciaPlantaCm: 12, distanciaLineaCm: 25, alturaCm: 35,
    diasACosecha: 120, rendimientoPorPlanta: 0.15, unidad: 'kg', ventana: 'puntual',
    companeras: ['zanahoria'], antagonistas: ['judia'],
    riego: 'Moderado; reducir al final para que engorde el bulbo.', plagas: 'Mildiu de la cebolla.',
    notas: 'Cosechar cuando la hoja se dobla y seca.',
  },
  {
    id: 'judia', nombreComun: 'Judía', nombreCientifico: 'Phaseolus vulgaris',
    icono: '🫘', familia: 'leguminosas', tipo: 'leguminosa',
    tempMinGerminacion: 12, tempOptima: 21, toleranciaHelada: 'sensible',
    texturaPreferida: ['franco', 'arenoso'], phMin: 6, phMax: 7.5, drenajeRequerido: 'medio',
    metodo: 'siembra_directa', sol: 'pleno_sol',
    distanciaPlantaCm: 15, distanciaLineaCm: 40, alturaCm: 40,
    diasACosecha: 65, rendimientoPorPlanta: 0.3, unidad: 'kg', ventana: 'continua', ventanaDias: 40,
    companeras: ['calabacin', 'zanahoria'], antagonistas: ['cebolla'],
    riego: 'Regular; evitar encharcar.', plagas: 'Pulgón.',
    notas: 'Fija nitrógeno; mejora el suelo para el cultivo siguiente.',
  },
  {
    id: 'albahaca', nombreComun: 'Albahaca', nombreCientifico: 'Ocimum basilicum',
    icono: '🌿', familia: 'labiadas', tipo: 'otro',
    tempMinGerminacion: 14, tempOptima: 22, toleranciaHelada: 'sensible',
    texturaPreferida: ['franco'], phMin: 6, phMax: 7, drenajeRequerido: 'bueno',
    metodo: 'siembra_directa', sol: 'pleno_sol',
    distanciaPlantaCm: 20, distanciaLineaCm: 25, alturaCm: 40,
    diasACosecha: 60, rendimientoPorPlanta: 4, unidad: 'manojos', ventana: 'continua', ventanaDias: 90,
    companeras: ['tomate', 'pimiento'], antagonistas: [],
    riego: 'Riego regular; no encharcar.', plagas: 'Pulgón.',
    notas: 'Pinzar flores para prolongar la hoja. Buena compañera del tomate.',
  },
  {
    id: 'patata', nombreComun: 'Patata', nombreCientifico: 'Solanum tuberosum',
    icono: '🥔', familia: 'solanáceas', tipo: 'raiz',
    tempMinGerminacion: 8, tempOptima: 18, toleranciaHelada: 'sensible',
    texturaPreferida: ['franco', 'arenoso'], phMin: 5.5, phMax: 6.5, drenajeRequerido: 'bueno',
    metodo: 'siembra_directa', sol: 'pleno_sol',
    distanciaPlantaCm: 30, distanciaLineaCm: 70, alturaCm: 60,
    diasACosecha: 110, rendimientoPorPlanta: 0.8, unidad: 'kg', ventana: 'puntual',
    companeras: ['judia'], antagonistas: ['tomate', 'calabacin'],
    riego: 'Riego regular; reducir al acercarse la cosecha para que no se pudran los tubérculos.',
    plagas: 'Escarabajo de la patata y mildiu; vigilar la hoja y no mojarla.',
    notas: 'Aporcar (cubrir el pie con tierra) para que los tubérculos no verdeen al sol.',
  },
]

export function buscarCultivo(id: string): Cultivo | undefined {
  return CULTIVOS.find((c) => c.id === id)
}
